param()

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$failures = [System.Collections.Generic.List[string]]::new()
$checks = 0

function Assert-Contains($Path, $Pattern, $Label) {
  $script:checks++
  $content = Get-Content -LiteralPath (Join-Path $Root $Path) -Raw
  if ($content -notmatch $Pattern) {
    $script:failures.Add("$Label ($Path)")
  }
}

function Assert-NotContains($Path, $Pattern, $Label) {
  $script:checks++
  $content = Get-Content -LiteralPath (Join-Path $Root $Path) -Raw
  if ($content -match $Pattern) {
    $script:failures.Add("$Label ($Path)")
  }
}

Assert-Contains "README.md" "codyx-orchestrator/dev/script/install-npm\.ps1" "README uses the dev branch for the npm-first Windows installer"
Assert-NotContains "README.md" "codyx-orchestrator/master/script/install\.sh" "README has no stale master installer URL"
Assert-Contains "README.md" "script/install-npm\.ps1" "README points normal Windows users to the npm installer"
Assert-Contains "README.md" "codyx-end-user-installer-windows-x64\.exe" "README points normal Windows users to the compiled end-user installer"
Assert-Contains "install.ps1" "script/install-npm\.ps1" "Root PowerShell installer is npm-first"
Assert-Contains "install.bat" "script/install-npm\.ps1" "Root CMD installer is npm-first"
Assert-NotContains "install.bat" "script/install\.ps1" "Root CMD installer does not trigger source checkout install"
Assert-NotContains "install.ps1" "Cody Pro|cody-pro|packages/opencode" "Root PowerShell installer has no Cody Pro branding"
Assert-NotContains "install.bat" "Cody Pro|cody-pro|packages/opencode" "Root CMD installer has no Cody Pro branding"
Assert-NotContains "script/install-npm.ps1" "Cody Pro|cody-pro|packages/opencode" "npm Windows installer has no Cody Pro branding"
Assert-Contains "script/install-npm.ps1" 'npm prefix -g' "npm installer uses npm prefix for npm 11 compatibility"
Assert-NotContains "script/install-npm.ps1" 'npm bin -g' "npm installer does not use removed npm bin command"
Assert-Contains "script/install-npm.ps1" '\[switch\]\$Launch' "npm installer can launch codyx after install"
Assert-Contains "script/install-npm.ps1" 'License Agreement' "npm installer shows the license agreement"
Assert-Contains "script/install-npm.ps1" 'Invoke-CodyxTraceCleanup' "npm installer cleans codyx traces when license is declined"
Assert-Contains "script/install-npm.ps1" 'CODY_ACCEPT_LICENSE' "npm installer supports explicit license acceptance for automation"
Assert-Contains "script/install-npm.ps1" 'Add-CodyxManagedTool "node" "winget" "OpenJS\.NodeJS\.LTS"' "npm installer records Node.js only when it installs Node.js"
Assert-Contains "script/install-npm.ps1" 'managedTools' "npm installer records Codyx-owned tools"
Assert-Contains "CODYX_INSTALL_UPDATE.md" "dev/script/install\.ps1" "Install guide uses the unified Windows installer"
Assert-Contains "CODYX_INSTALL_UPDATE.md" "dev/script/install-npm\.ps1" "Install guide documents the npm-first Windows installer"
Assert-NotContains "CODYX_INSTALL_UPDATE.md" "master/install\.ps1" "Install guide has no deprecated master URL"
Assert-Contains "CODYX_INSTALL_UPDATE.md" 'End-user installer `\.exe`' "Install guide lists the compiled end-user installer"
Assert-Contains "CODYX_INSTALL_UPDATE.md" "release manifest on every start" "Install guide documents compiled shim update checks"
Assert-Contains "script/install-compiled.ps1" "Compiled release assets" "Compiled installer announces compiled release asset mode"
Assert-Contains "script/install-compiled.ps1" "codyx-release-manifest\.json" "Compiled installer consumes the release manifest"
Assert-Contains "script/install-compiled.ps1" "Get-FileHash" "Compiled installer verifies downloaded assets by SHA256"
Assert-Contains "script/install-compiled.ps1" "Test-InstalledAssetCurrent" "Compiled installer skips re-downloads when the marker hash matches"
Assert-Contains "script/install-compiled.ps1" "Using explicit release manifest" "Compiled installer supports explicit local release manifests"
Assert-Contains "script/install-compiled.ps1" 'Test-Path -LiteralPath \$url -PathType Leaf' "Compiled installer can read a local manifest file"
Assert-Contains "script/install-compiled.ps1" 'Join-Path \$manifestBundle.SourceDir \$asset.file' "Compiled installer can load assets beside a local manifest"
Assert-Contains "script/install-compiled.ps1" "NoPathUpdate" "Compiled installer has a no-PATH mode for smoke tests"
Assert-Contains "script/install-compiled.ps1" "NoShortcuts" "Compiled installer has a no-shortcuts mode for smoke tests"
Assert-Contains "script/install-compiled.ps1" "CODYX_SKIP_UPDATE" "Compiled shims support skipping update checks for diagnostics"
Assert-Contains "script/install-compiled.ps1" "CODY_DISABLE_AUTOUPDATE" "Compiled shims disable unsafe in-process binary self-update"
Assert-Contains "script/install-compiled.ps1" 'if /I "%~1"=="uninstall" goto codyx_run' "Compiled CMD shim skips update preflight for uninstall"
Assert-Contains "script/install-compiled.ps1" "adminUninstall" "Compiled installer records admin uninstall metadata"
Assert-Contains "script/install-compiled.ps1" 'installer-verification\.ps1' "Compiled installer loads the shared email verification helper"
Assert-Contains "script/install-compiled.ps1" 'verificationSourceFull[\s\S]*verificationDestinationFull[\s\S]*Copy-Item -LiteralPath \$verificationSource' "Compiled updater skips copying installer-verification.ps1 onto itself"
Assert-Contains "script/install-compiled.ps1" 'Ensure-UserMemo[\s\S]*Invoke-InstallerVerification' "Compiled installer collects the user name before verification"
Assert-Contains "script/install-compiled.ps1" 'NonInteractive = -not \(Test-InteractiveHost\)' "Compiled installer detects noninteractive verification"
Assert-Contains "script/install-compiled.ps1" 'if \(-not \$result\.Success\)[\s\S]*Email verification is required' "Compiled installer stops when verification fails"
Assert-Contains "script/install-compiled.ps1" 'verification[\s\S]*installId[\s\S]*receiptPath' "Compiled installer marker records verification metadata"
Assert-Contains "script/install-compiled.ps1" "\.codyx-install-marker" "Compiled installer writes the local uninstall marker"
Assert-NotContains "script/install-compiled.ps1" "git clone|bun install|script/install\.ps1" "Compiled installer does not clone source or install Bun"
Assert-Contains "CODYX_LAUNCHER_REFERENCE.md" 'dist\\luncher\.exe' "Launcher reference guide records the old launcher baseline"
Assert-Contains "CODYX_LAUNCHER_REFERENCE.md" 'Open CLI`, `Open Web UI`, and `Uninstall` must stay disabled until the installed command exists' "Launcher reference guide protects incomplete install actions"
Assert-Contains "packages/end-user-installer/Codyx.EndUserInstaller.csproj" "install-compiled\.ps1" "Compiled installer UI embeds the compiled asset installer script"
Assert-Contains "packages/end-user-installer/Codyx.EndUserInstaller.csproj" "installer-verification\.ps1" "Compiled installer UI embeds the verification helper"
Assert-Contains "packages/end-user-installer/Codyx.EndUserInstaller.csproj" 'Assets\\mufasa\.png' "Compiled installer UI bundles the Mufasa image"
Assert-Contains "packages/end-user-installer/Program.cs" "Agree and install" "Compiled installer UI requires explicit license agreement"
Assert-Contains "packages/end-user-installer/Program.cs" "Open Web UI" "Compiled installer UI exposes a Web UI launch button"
Assert-Contains "packages/end-user-installer/Program.cs" "LocalManifestPath" "Compiled installer UI detects a local release manifest beside the exe"
Assert-Contains "packages/end-user-installer/Program.cs" "-ManifestUrl" "Compiled installer UI forwards the local release manifest to the installer script"
Assert-Contains "packages/end-user-installer/Program.cs" 'RedirectStandardInput = true' "Compiled installer UI accepts verification answers"
Assert-Contains "packages/end-user-installer/Program.cs" 'CODY_LAUNCHER_UI' "Compiled installer UI enables launcher prompt mode"
Assert-Contains "packages/end-user-installer/Program.cs" '::codyx-prompt::' "Compiled installer UI reads prompt markers"
Assert-Contains "packages/end-user-installer/Program.cs" 'SendPromptAnswer' "Compiled installer UI sends name, email, and code answers"
Assert-Contains "packages/end-user-installer/Program.cs" 'BuildBanner[\s\S]*Codyx-Orchestrator[\s\S]*BuildShimmerBrush' "Compiled installer UI follows the Mufasa launcher visual reference"
Assert-Contains "packages/end-user-installer/Program.cs" 'Assets/mufasa\.png[\s\S]*Welcome to Codyx[\s\S]*by M\. Farid \(Mufasa\)' "Compiled installer UI keeps the Mufasa image and welcome copy"
Assert-Contains "packages/end-user-installer/Program.cs" 'promptChangeEmail[\s\S]*change-email[\s\S]*promptResend[\s\S]*resend' "Compiled installer UI exposes change-email and resend buttons"
Assert-Contains "packages/end-user-installer/Program.cs" 'codeBoxes = new TextBox\[6\][\s\S]*BuildCodeInputs[\s\S]*PreviewTextInput[\s\S]*char\.IsDigit' "Compiled installer UI uses six digit-only verification boxes"
Assert-Contains "packages/end-user-installer/Program.cs" 'Clipboard\.GetText\(\)\.Trim\(\)[\s\S]*text\.Length == 6[\s\S]*SendPromptAnswer\(\)' "Compiled installer UI supports pasting a six-digit verification code"
Assert-Contains "packages/end-user-installer/Program.cs" 'promptIsCode \? string\.Concat\(codeBoxes\.Select' "Compiled installer UI sends the six code boxes as one verification value"
Assert-Contains "packages/end-user-installer/Program.cs" 'SetInstalledActions\(false\)[\s\S]*RefreshInstalledActions\(\)' "Compiled installer UI disables launch actions until install completion is verified"
Assert-Contains "packages/end-user-installer/Program.cs" 'Activated \+= \(_, _\) => RefreshInstalledActions\(\)' "Compiled installer UI refreshes installed state when the window regains focus"
Assert-Contains "packages/end-user-installer/Program.cs" 'Uninstall started\. Install/update is needed' "Compiled installer UI disables launch actions immediately after uninstall starts"
Assert-Contains "packages/end-user-installer/Program.cs" 'uninstallInProgress[\s\S]*SetInstalledActions\(health\.Ready && !uninstallInProgress\)' "Compiled installer UI keeps launch actions disabled while uninstall is in progress"
Assert-Contains "packages/end-user-installer/Program.cs" 'IOPath\.GetTempPath\(\)' "Compiled installer UI launches uninstall outside the install bin directory"
Assert-Contains "packages/end-user-installer/Program.cs" 'GetInstallHealth[\s\S]*InstalledShimPath\(\)[\s\S]*InstalledCliPath\(\)[\s\S]*InstalledUpdaterPath\(\)[\s\S]*InstalledVerificationHelperPath\(\)[\s\S]*InstallerMarkerPath\(\)[\s\S]*RootMarkerPath\(\)[\s\S]*VerificationReceiptPath\(\)' "Compiled installer UI gates launch actions on a complete installed state"
Assert-Contains "packages/end-user-installer/Program.cs" 'AddIfFileMissingRequiredText' "Compiled installer UI rejects stale marker and receipt files"
Assert-Contains "packages/end-user-installer/Program.cs" 'RunEmbeddedInstallPreflightAsync[\s\S]*ExtractScripts\(\)[\s\S]*-AcceptLicense -Quiet -NoLaunch' "Compiled installer UI repairs with embedded current updater before launching CLI or Web UI"
Assert-Contains "packages/end-user-installer/Program.cs" 'primary\.Content = health\.Ready \? "Check / repair update" : "Agree and install"' "Compiled installer UI shows repair/update instead of fresh install when already healthy"
Assert-Contains "packages/codyx/src/server/agent/rest.ts" 'x-cody-cli-local[\s\S]*LOCAL_CLI_USER_ID' "Hono agent routes accept trusted local CLI requests"
Assert-Contains "packages/codyx/src/server/routes/instance/httpapi/handlers/agent.ts" 'x-cody-cli-local[\s\S]*LOCAL_CLI_USER_ID' "Effect HTTP API agent routes accept trusted local CLI requests"
Assert-Contains "script/install.ps1" 'install-codyx-global\.ps1.*-Root \$Root' "Windows installer propagates InstallRoot"
Assert-Contains "script/install.ps1" '\$env:ComSpec /d /s /c \$versionCommand' "Windows installer verifies the global shim through cmd"
Assert-NotContains "script/install.ps1" '\& \$GlobalCmd --version 2>\$null' "Windows health check does not convert version stderr into a PowerShell error"
Assert-NotContains "script/install.ps1" '\& powershell ' "Windows installer has no ambiguous bare PowerShell invocation"
Assert-NotContains "script/install.ps1" '(git clone|git fetch|git switch|git pull|bun install|bun run build)[^\r\n]*2>&1' "Windows native tools do not merge stderr into PowerShell errors"
Assert-Contains "script/install.ps1" '\$CheckoutRoot.*Split-Path -Parent \$PSScriptRoot' "Windows installer detects a local checkout"
Assert-Contains "script/install.ps1" 'Test-BunVersion' "Windows installer enforces the supported Bun version"
Assert-Contains "script/install.ps1" 'VERIFICATION_URL = "https://install\.kingkung\.men"' "Windows installer uses the production verification service"
Assert-Contains "script/install.ps1" 'installer-verification\.ps1' "Windows installer loads the verification helper"
Assert-Contains "script/install.ps1" 'NonInteractive = -not \(Test-InteractiveHost\)' "Windows installer detects noninteractive verification"
Assert-Contains "script/install.ps1" 'CODY_LAUNCHER_UI -eq "1"[\s\S]*return \$true' "Windows installer treats the WPF answer box as interactive"
Assert-Contains "script/install.ps1" 'if \(-not \$verificationResult\.Success\)' "Windows installer stops when verification fails"
Assert-Contains "script/install.ps1" 'Bun 1\.3\.13\+ found\.[\s\S]*Loading installer email verification[\s\S]*cloudflared' "Windows verification runs after Bun and before cloudflared"
Assert-Contains "script/install.ps1" 'License Agreement' "Windows source installer shows the license agreement"
Assert-Contains "script/install.ps1" 'Invoke-CodyxTraceCleanup' "Windows source installer cleans codyx traces when license is declined"
Assert-Contains "script/install.ps1" 'CODY_ACCEPT_LICENSE' "Windows source installer supports explicit license acceptance for automation"
Assert-Contains "script/install.ps1" '::codyx-prompt::\$Prompt' "Windows source installer emits launcher-readable prompt markers"
Assert-Contains "script/installer-verification.ps1" '::codyx-prompt::\$Prompt' "Verification helper emits launcher-readable prompt markers"
Assert-Contains "script/installer-verification.ps1" 'Email address \(privacy: \$privacyUrl, or ''cancel''\)' "Verification helper shows the privacy URL in the email prompt"
Assert-Contains "script/installer-verification.ps1" 'CODY_LAUNCHER_UI -eq "1"[\s\S]*Privacy: \$privacyUrl' "Verification helper prints a plain privacy URL in launcher UI logs"
Assert-Contains "script/installer-verification.ps1" 'Get-EmailTypoSuggestion[\s\S]*agmail\.com[\s\S]*Use email \$candidateEmail\? \[Y/n\]' "Verification helper confirms email and warns common typos before sending"
Assert-Contains "script/installer-verification.ps1" 'Get-CodyxMachineId[\s\S]*MachineGuid' "Verification helper captures Windows Machine ID during install"
Assert-Contains "script/installer-verification.ps1" 'machine_id = \$machineId' "Verification helper sends Machine ID during challenge and code verification"
Assert-Contains "script/install.ps1" 'Add-CodyxManagedTool \$Name "winget" \$WingetId' "Windows source installer records winget tools it installs"
Assert-Contains "script/install.ps1" 'Add-CodyxManagedTool "bun" "path"' "Windows source installer records Bun only when it installs Bun"
Assert-Contains "script/install.ps1" 'Add-CodyxManagedTool "cloudflared" "winget" "Cloudflare\.cloudflared"' "Windows source installer records cloudflared only when it installs cloudflared"
Assert-Contains "script/install.ps1" 'Write-CodyxAdminUninstallMarker' "Windows source installer records admin uninstall metadata in install markers"
Assert-Contains "script/install.ps1" 'commandsPath = "/v1/commands"[\s\S]*acknowledgePath = "/v1/acknowledge"[\s\S]*completePath = "/v1/complete"' "Windows source installer marker points at remote admin uninstall endpoints"
Assert-Contains "script/update-install-marker.ps1" 'installed[\s\S]*pathAdds[\s\S]*shortcuts[\s\S]*shims[\s\S]*markerPaths[\s\S]*managedTools' "Live marker refresh tracks installed paths, PATH entries, shims, shortcuts, marker paths, and managed tools"
Assert-Contains "script/install.ps1" 'update-install-marker\.ps1' "Windows source installer refreshes the live uninstall marker"
Assert-Contains "script/install-npm.ps1" 'jsInstall[\s\S]*codyx-ai[\s\S]*Update-CodyxNpmInstallMarker' "npm installer records JS package installation details"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'installMarkers: string\[\][\s\S]*for \(const marker of targets\.installMarkers\)' "CLI uninstall removes every recorded install marker"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'No uninstall errors\. No removal log was written\.' "CLI uninstall does not recreate a codyx home folder after clean cleanup"
Assert-Contains "install.ps1" 'AcceptLicense' "Root PowerShell installer forwards license acceptance"
Assert-Contains "install.bat" 'CODY_ACCEPT_LICENSE' "Root CMD installer forwards license acceptance"
Assert-NotContains "script/install.ps1" '[^\x00-\x7F]' "Streamed Windows installer is ASCII-safe for Windows PowerShell"
Assert-Contains "codyx.cmd" 'CODY_ORIGINAL_HTTP_PROXY=!HTTP_PROXY!' "Windows launcher preserves the user's HTTP proxy"
Assert-Contains "codyx.cmd" 'if not "%CODY_PROXY_ENABLED%"=="1" \([\s\S]*HTTP_PROXY=!CODY_ORIGINAL_HTTP_PROXY![\s\S]*HTTPS_PROXY=!CODY_ORIGINAL_HTTPS_PROXY!' "Disabled Cody proxy does not hijack update checks"
Assert-Contains "codyx.cmd" 'script\\launcher-menu\.ps1' "Windows command launcher delegates the interactive menu to launcher-menu.ps1"
Assert-Contains "script/launcher.ps1" 'codyx-orchestrator\.git' "Standalone launcher uses the codyx-orchestrator repo"
Assert-Contains "script/launcher.ps1" 'else \{ "dev" \}' "Standalone launcher defaults to the dev branch"
Assert-Contains "script/launcher.ps1" 'Resolve-InstallRoot' "Standalone launcher resolves a safe source checkout root"
Assert-Contains "script/launcher.ps1" 'Join-Path \$defaultRoot "source"' "Standalone launcher avoids runtime app data when the default root is not a checkout"
Assert-Contains "script/launcher.ps1" 'Test-CodyxInstallComplete' "Standalone launcher checks for a completed source install"
Assert-Contains "script/launcher.ps1" '\.codyx-install-marker' "Standalone launcher resumes first-run setup after an interrupted clone"
Assert-Contains "script/launcher.ps1" 'Install-WithWinget "git" "Git\.Git" "Git"' "Standalone launcher installs Git automatically when winget is available"
Assert-Contains "script/launcher.ps1" 'Get-PortableGitDownloadUrls[\s\S]*MinGit-.\*-64-bit' "Standalone launcher falls back to portable MinGit when package managers are unavailable"
Assert-Contains "script/launcher.ps1" 'Get-PortableGitDownloadUrls[\s\S]*v2\.55\.0\.windows\.2' "Standalone launcher has direct portable Git download fallbacks when GitHub API is unavailable"
Assert-Contains "script/launcher.ps1" 'CODY_PORTABLE_GIT_ROOT' "Standalone launcher records portable Git for the follow-up installer"
Assert-Contains "script/launcher.ps1" 'Invoke-Native[\s\S]*ForEach-Object \{ Write-Host \$_ \}[\s\S]*return \[int\]\$LASTEXITCODE' "Standalone launcher native helper streams stdout but returns only the exit code"
Assert-Contains "script/launcher.ps1" 'bun\.sh/install\.ps1' "Standalone launcher installs Bun automatically"
Assert-Contains "script/launcher.ps1" 'Invoke-FirstRunInstall' "Standalone launcher runs the normal installer on first launch"
Assert-Contains "script/launcher.ps1" '\$AcceptLicense -or \$env:CODY_ACCEPT_LICENSE -eq "1"' "Standalone launcher requires explicit license acceptance before forwarding it"
Assert-Contains "script/launcher.ps1" 'broken checkout does not launch' "Standalone launcher stops after repair failure"
Assert-Contains "script/launcher.ps1" 'Get-CodyxSparseCheckoutPaths[\s\S]*/packages/app/[\s\S]*/packages/codyx/[\s\S]*/packages/script/[\s\S]*!\*\*/\*\.test\.ts' "Standalone launcher slim checkout keeps runtime workspaces and excludes tests"
Assert-Contains "script/launcher.ps1" '"/packages/script/"' "Standalone launcher keeps the script workspace required by the source build"
Assert-Contains "script/launcher.ps1" '!/packages/codyx/script/httpapi-exercise\.ts' "Standalone launcher excludes developer-only httpapi exercise script from slim checkout"
Assert-NotContains "script/launcher.ps1" '"/packages/(gitlab-auth|poe-auth)/"' "Standalone launcher slim checkout excludes optional auth workspaces"
Assert-Contains "script/launcher.ps1" 'Enable-CodyxSlimCheckout[\s\S]*sparse-checkout", "set", "--no-cone"' "Standalone launcher can convert existing installs to explicit slim checkout"
Assert-Contains "script/launcher.ps1" 'Disable-CodyxGitPush[\s\S]*DISABLED-BY-CODYX-END-USER-INSTALL' "Standalone launcher disables accidental pushes from end-user checkouts"
Assert-Contains "script/launcher.ps1" 'Remove-CodyxEndUserSourceExtras[\s\S]*packages\\codyx\\test[\s\S]*packages\\gitlab-auth' "Standalone launcher removes leftover non-end-user source after sparse checkout"
Assert-Contains "script/launcher.ps1" 'Remove-CodyxEndUserSourceExtras[\s\S]*packages\\codyx\\script\\httpapi-exercise\.ts' "Standalone launcher removes leftover developer-only httpapi exercise script"
Assert-NotContains "script/launcher.ps1" 'Remove-CodyxEndUserSourceExtras[\s\S]*packages\\script' "Standalone launcher does not delete the script workspace required by the source build"
Assert-Contains "script/launcher.ps1" 'update-install-marker\.ps1' "Standalone launcher refreshes the live uninstall marker"
Assert-Contains "script/launcher.ps1" '\$env:HUSKY = "0"[\s\S]*"install", "--no-save", "--force"' "Standalone launcher disables Husky hooks during dependency refresh"
Assert-Contains "script/install.ps1" 'Get-PortableGitDownloadUrls[\s\S]*MinGit-.\*-64-bit' "Windows installer falls back to portable MinGit when package managers are unavailable"
Assert-Contains "script/install.ps1" 'Get-PortableGitDownloadUrls[\s\S]*v2\.55\.0\.windows\.2' "Windows installer has direct portable Git download fallbacks when GitHub API is unavailable"
Assert-Contains "script/install.ps1" 'Add-CodyxManagedTool "git" "path"' "Windows installer records portable Git for clean uninstall"
Assert-Contains "script/install.ps1" 'Get-CodyxSparseCheckoutPaths[\s\S]*/packages/app/[\s\S]*/packages/codyx/[\s\S]*/packages/script/[\s\S]*!\*\*/\*\.test\.ts' "Windows installer slim checkout keeps runtime workspaces and excludes tests"
Assert-Contains "script/install.ps1" '"/packages/script/"' "Windows installer keeps the script workspace required by the source build"
Assert-Contains "script/install.ps1" '!/packages/codyx/script/httpapi-exercise\.ts' "Windows installer excludes developer-only httpapi exercise script from slim checkout"
Assert-NotContains "script/install.ps1" '"/packages/(gitlab-auth|poe-auth)/"' "Windows installer slim checkout excludes optional auth workspaces"
Assert-Contains "script/install.ps1" 'Sync-InstallCheckout[\s\S]*Enable-CodyxSlimCheckout' "Windows installer converts existing standalone checkouts to slim checkout"
Assert-Contains "script/install.ps1" 'Remove-CodyxEndUserSourceExtras[\s\S]*packages\\codyx\\script\\httpapi-exercise\.ts' "Windows installer removes leftover developer-only httpapi exercise script"
Assert-NotContains "script/install.ps1" 'Remove-CodyxEndUserSourceExtras[\s\S]*packages\\script' "Windows installer does not delete the script workspace required by the source build"
Assert-Contains "script/update-progress.ps1" '"/packages/script/"' "CMD update progress keeps the script workspace required by the source build"
Assert-Contains "script/update-progress.ps1" '!/packages/codyx/script/httpapi-exercise\.ts' "CMD update progress excludes developer-only httpapi exercise script from slim checkout"
Assert-Contains "script/update-progress.ps1" 'Invoke-Native[\s\S]*ForEach-Object \{ Write-Host \$_ \}[\s\S]*return \[int\]\$LASTEXITCODE' "CMD update progress native helper streams stdout but returns only the exit code"
Assert-Contains "script/update-progress.ps1" 'Enable-CodyxSlimCheckout[\s\S]*sparse-checkout", "set", "--no-cone"' "CMD update progress reapplies explicit slim checkout after pull or repair"
Assert-Contains "script/update-progress.ps1" 'Disable-CodyxGitPush[\s\S]*DISABLED-BY-CODYX-END-USER-INSTALL' "CMD update progress disables accidental pushes from end-user checkouts"
Assert-Contains "script/update-progress.ps1" 'Remove-CodyxEndUserSourceExtras[\s\S]*packages\\codyx\\script\\httpapi-exercise\.ts' "CMD update progress removes leftover developer-only httpapi exercise script"
Assert-NotContains "script/update-progress.ps1" 'Remove-CodyxEndUserSourceExtras[\s\S]*packages\\script' "CMD update progress does not delete the script workspace required by the source build"
Assert-Contains "script/install.ps1" '\$env:HUSKY = "0"[\s\S]*bun install' "Windows installer disables Husky hooks during dependency install"
Assert-NotContains "packages/codyx/package.json" '@cody/(gitlab-auth|poe-auth)|@gitlab/opencode-gitlab-auth' "codyx package manifest does not require removed end-user auth workspaces"
Assert-NotContains "packages/codyx/src/plugin/index.ts" '@cody/(gitlab-auth|poe-auth)|GitlabAuthPlugin|PoeAuthPlugin' "Built-in plugin list does not import removed optional auth workspaces"
Assert-Contains "script/launcher.ps1" 'packages\\codyx\\node_modules\\drizzle-orm\\sqlite-core\\index\.js' "Standalone launcher repairs missing runtime dependencies"
Assert-Contains "script/launcher.ps1" 'node_modules\\@anthropic-ai\\sdk\\version\.mjs' "Standalone launcher repairs incomplete Bun package extraction"
Assert-Contains "codyx.cmd" 'Repair failed\. Stop here so the broken checkout does not launch' "CMD launcher stops after repair failure"
Assert-Contains "codyx.cmd" 'Refreshing dependencies after update' "CMD launcher refreshes dependencies after repair or pull"
Assert-Contains "codyx.cmd" 'packages\\codyx\\node_modules\\drizzle-orm\\sqlite-core\\index\.js' "CMD launcher repairs missing runtime dependencies"
Assert-Contains "codyx.cmd" '@anthropic-ai\\sdk\\version\.mjs' "CMD launcher repairs incomplete Bun package extraction"
Assert-Contains "codyx.cmd" 'install --no-save --force --cwd "%ROOT%\."' "CMD launcher force-installs without rewriting tracked lockfiles"
Assert-Contains "codyx.cmd" 'install --no-save --cwd "%ROOT%\."' "CMD launcher passes Bun a Windows-safe checkout directory without rewriting tracked lockfiles"
Assert-Contains "codyx.cmd" 'set "HUSKY=0"[\s\S]*update-install-marker\.ps1' "CMD launcher disables Husky during dependency refresh and updates the live marker"
Assert-Contains "script/launcher.ps1" '"clone", "--filter=blob:none", "--no-checkout", "--quiet", "--branch"' "Standalone launcher suppresses git clone progress on stderr"
Assert-Contains "script/launcher.ps1" 'update-progress\.ps1"[\s\S]*"-Action", "repair"' "Standalone launcher repairs dirty install checkouts before launch"
Assert-Contains "script/launcher.ps1" 'git" @\("update-index", "-q", "--refresh"\)' "Standalone launcher refreshes the Git index before dirty-checking tracked files"
Assert-Contains "script/launcher.ps1" 'if \(\$needsFirstRunInstall\) \{[\s\S]*Test-CodyxCheckout \$InstallRoot[\s\S]*Sync-Checkout[\s\S]*Invoke-FirstRunInstall' "Standalone launcher updates incomplete first-run checkouts before verification"
Assert-Contains "script/update-progress.ps1" 'git fetch origin \$Branch --quiet[\s\S]*git reset --hard "origin/\$Branch"' "Repair script refreshes and resets the install checkout directly"
Assert-Contains "script/launcher-menu.ps1" 'CLI \(Terminal UI\)' "Interactive launcher menu keeps the CLI option"
Assert-Contains "script/launcher-menu.ps1" 'Web UI \(Browser\)' "Interactive launcher menu keeps the Web UI option"
Assert-Contains ".github/workflows/publish.yml" 'build-launcher-windows' "Release workflow builds the Windows launcher exe"
Assert-Contains ".github/workflows/publish.yml" 'codyx-launcher-windows-x64\.exe' "Release workflow publishes the Windows launcher exe"
Assert-Contains ".github/workflows/publish.yml" 'build-end-user-installer-windows' "Release workflow builds the compiled end-user installer exe"
Assert-Contains ".github/workflows/publish.yml" 'codyx-end-user-installer-windows-x64\.exe' "Release workflow publishes the compiled end-user installer exe"
Assert-Contains ".github/workflows/publish.yml" 'script/create-release-manifest\.ts' "Release workflow generates the release manifest"
Assert-Contains ".github/workflows/publish.yml" 'codyx-release-manifest\.json' "Release workflow uploads the release manifest"
Assert-Contains ".github/workflows/publish.yml" 'pattern: cody-desktop-\*' "Release workflow collects desktop assets for the manifest"
Assert-Contains ".github/workflows/publish.yml" 'name: codyx-android' "Release workflow collects Android assets for the manifest"
Assert-Contains ".github/workflows/publish.yml" 'actions/setup-dotnet@v4' "Release workflow sets up .NET for the Windows launcher"
Assert-Contains ".github/workflows/publish.yml" 'dotnet publish packages\\launcher\\Codyx\.Launcher\.csproj' "Release workflow publishes the .NET launcher"
Assert-Contains ".github/workflows/publish.yml" '(?s)build-launcher-windows:.*?if: env\.AZURE_CLIENT_ID != '''' && env\.AZURE_TENANT_ID != '''' && env\.AZURE_SUBSCRIPTION_ID != ''''' "Release workflow skips Azure login when signing secrets are absent"
Assert-Contains ".github/workflows/publish.yml" '(?s)sign-cli-windows:.*?azure/artifact-signing-action@v1\s+if: env\.AZURE_CLIENT_ID != '''' && env\.AZURE_TENANT_ID != '''' && env\.AZURE_SUBSCRIPTION_ID != ''''' "Release workflow skips Windows CLI signing when signing secrets are absent"
Assert-Contains ".github/workflows/publish.yml" "codyx-ai-windows-x64-baseline\.zip" "Release workflow packages codyx-ai Windows release assets"
Assert-NotContains ".github/workflows/publish.yml" "cody-windows" "Release workflow has no stale cody-windows asset names"
Assert-NotContains ".github/workflows/publish.yml" 'Invoke-ps2exe' "Release workflow no longer builds the launcher through PS2EXE"
Assert-Contains ".github/workflows/publish.yml" 'GH_REPO: \$\{\{ needs\.version\.outputs\.repo \}\}' "Electron packaging receives the release repo for updater metadata"
Assert-Contains ".github/workflows/publish.yml" 'build-android' "Release workflow builds Android artifacts"
Assert-Contains ".github/workflows/publish.yml" 'packages/android/app-release\*\.aab' "Release workflow publishes Android app bundles"
Assert-NotContains ".github/workflows/publish.yml" 'packages\\cody\\dist|packages/cody/dist' "Release workflow has no stale packages/cody artifact paths"
Assert-Contains "packages/desktop/electron-builder.config.ts" 'process\.env\.GH_REPO' "Electron updater publishes to the selected release repo"
Assert-NotContains "packages/desktop/electron-builder.config.ts" 'anomalyco' "Electron updater no longer publishes to upstream anomalyco repos"
Assert-Contains "packages/desktop/src/main/updater.ts" 'checkForUpdatesInBackground' "Electron updater supports startup background checks"
Assert-Contains "packages/desktop/src/main/updater.ts" 'autoInstallOnAppQuit = true' "Electron updater installs downloaded updates on quit"
Assert-Contains "packages/launcher/Codyx.Launcher.csproj" '<UseWPF>true</UseWPF>' "Windows launcher is a WPF app"
Assert-Contains "packages/launcher/Codyx.Launcher.csproj" 'Assets\\mufasa\.png' "Windows launcher bundles the Mufasa image"
Assert-Contains "packages/launcher/Codyx.Launcher.csproj" 'launcher\.ps1' "Windows launcher embeds the PowerShell bootstrapper"
Assert-Contains "packages/launcher/Program.cs" 'License agreement' "Windows launcher shows a license panel"
Assert-Contains "packages/launcher/Program.cs" 'Agree and continue' "Windows launcher requires explicit agreement"
Assert-Contains "packages/launcher/Program.cs" 'identity and email verification' "Windows launcher keeps verification visible"
Assert-Contains "packages/launcher/Program.cs" 'RedirectStandardInput = true' "Windows launcher accepts setup answers inside the UI"
Assert-Contains "packages/launcher/Program.cs" 'setupPromptActive' "Windows launcher only accepts answers while a setup prompt is active"
Assert-Contains "packages/launcher/Program.cs" 'Waiting for installer prompt' "Windows launcher does not invite blind input before prompts"
Assert-Contains "packages/launcher/Program.cs" 'setupCancelButton[\s\S]*SendSetupInput\("cancel"\)' "Windows launcher provides a real cancel button for cancellable prompts"
Assert-Contains "packages/launcher/Program.cs" 'RenderSetupPrompt[\s\S]*new Hyperlink[\s\S]*OpenUri' "Windows launcher renders privacy prompt URLs as clickable links"
Assert-NotContains "packages/launcher/Program.cs" 'Open interactive setup' "Windows launcher does not fall back to first-run setup after update failure"
Assert-Contains "packages/launcher/Program.cs" 'Retry update check' "Windows launcher retries update failures without reopening setup"
Assert-NotContains "packages/launcher/Program.cs" 'Starting setup with explicit license acceptance' "Windows launcher avoids confusing setup wording"
Assert-Contains "packages/launcher/Program.cs" 'Starting first-run setup after license acceptance' "Windows launcher labels first-run setup accurately"
Assert-Contains "packages/launcher/Program.cs" 'BuildLaunchChoicePanel' "Windows launcher shows launch choices inside the WPF window"
Assert-Contains "packages/launcher/Program.cs" 'SystemParameters\.WorkArea' "Windows launcher sizes itself to the visible screen"
Assert-Contains "packages/launcher/Program.cs" 'new ScrollViewer' "Windows launcher keeps all setup content reachable on smaller screens"
Assert-Contains "packages/launcher/Program.cs" 'Terminal UI' "Windows launcher has a Terminal UI button"
Assert-Contains "packages/launcher/Program.cs" 'Web UI' "Windows launcher has a Web UI button"
Assert-Contains "packages/launcher/Program.cs" 'ShowLaunchChoices\(\);[\s\S]*codyx setup finished\. Choose how to start\.' "Windows launcher shows choices after first-run setup"
Assert-Contains "packages/launcher/Program.cs" 'ShowLaunchChoices\(\);[\s\S]*codyx is ready\. Choose how to start\.' "Windows launcher shows choices after update checks"
Assert-NotContains "packages/launcher/Program.cs" 'LaunchCodyx\(true\);|LaunchCodyx\(false\);' "Windows launcher no longer auto-launches past the choice screen"
Assert-Contains "codyx.cmd" '--launcher-web' "CMD launcher exposes a direct Web UI branch for the WPF launcher"
Assert-Contains "codyx.cmd" 'if /I "%~1"=="--launcher-web"[\s\S]*packages\\app" build[\s\S]*"%BUN%" run --cwd "%ROOT%packages\\codyx" --conditions=browser src\\index\.ts web' "Direct Web UI branch builds and starts the web app"
Assert-Contains "packages/launcher/Program.cs" 'BeginUninstallAsync' "Windows launcher has an uninstall button flow"
Assert-Contains "packages/launcher/Program.cs" 'WriteTempUninstallScript' "Windows launcher uninstalls from a temp cleanup script"
Assert-Contains "packages/launcher/Program.cs" 'codyx-uninstall-' "Windows launcher writes uninstall cleanup outside the install root"
Assert-Contains "packages/launcher/Program.cs" 'Invoke-CodyxManagedToolCleanup' "Windows launcher temp uninstall reads Codyx-managed tools"
Assert-Contains "packages/launcher/Program.cs" 'Remove-Item -LiteralPath ''\$escapedSelf''' "Windows launcher temp uninstall removes its own script"
Assert-Contains "packages/launcher/Program.cs" 'WaitForExit\(20000\)' "Windows launcher npm cleanup is bounded during uninstall"
Assert-Contains "packages/launcher/Program.cs" 'codyx uninstall cleanup finished' "Windows launcher uninstall reports a final completion line"
Assert-Contains "packages/codyx/src/cli/logo.ts" '╔═╗╔═╗╔╦╗╦ ╦═╗ ╦─[\s\S]*╔═╗╦═╗╔═╗╦ ╦╔═╗╔═╗╔╦╗╦═╗╔═╗╔╦╗╔═╗╦═╗' "Codyx banner uses the stylized orchestrator name"
Assert-Contains "packages/codyx/src/cli/cmd/tui/component/logo.tsx" 'build\(codyX\)' "TUI banner uses the Codyx logo shape"
Assert-Contains "packages/codyx/src/cli/ui.ts" 'const glyphs = codyX' "CLI banner uses the Codyx logo shape"
Assert-Contains "packages/launcher/Program.cs" '-NoLaunch' "Windows launcher completes setup before launching codyx"
Assert-NotContains "packages/launcher/Program.cs" 'CODY_FIRST_CHAT_PROMPT' "Windows launcher no longer relies on the removed TUI first-chat flag"
Assert-NotContains "packages/codyx/src/cli/cmd/tui/app.tsx" 'first_system_init_prompt_answered_v2|CODY_FIRST_CHAT_PROMPT' "TUI no longer owns the first-chat init prompt"
Assert-Contains "packages/codyx/src/session/prompt.ts" 'const firstInitYes = "Yes, start"' "Session first-chat prompt can start /init"
Assert-Contains "packages/codyx/src/session/prompt.ts" 'const firstInitNo = "Not now"' "Session first-chat prompt supports skipping /init"
Assert-Contains "packages/codyx/src/session/prompt.ts" 'would you like Codyx to collect useful information' "Session first-chat prompt explains the system scan"
Assert-Contains "packages/codyx/src/session/prompt.ts" 'Skip this for now\. You can run /init whenever you want\.' "Session first-chat prompt explains the later /init path"
Assert-Contains "packages/android/twa-manifest.json" '"host": "app\.codyx\.ai"' "Android package opens the hosted codyx PWA"
Assert-Contains "packages/android/twa-manifest.json" '"fallbackType": "customtabs"' "Android package has a browser fallback before TWA verification"
Assert-Contains "packages/android/package.json" '--manifest twa-manifest\.json' "Android package scripts pass Bubblewrap the manifest file"
Assert-NotContains ".github/workflows/publish.yml" '--manifest \.' "Release workflow does not pass Bubblewrap a directory as the manifest"
Assert-Contains "script/installer-verification.ps1" 'receipts/validate' "Verification helper validates saved receipts online"
Assert-Contains "script/installer-verification.ps1" 'change-email, retry, or cancel' "Verification helper exposes recovery commands"
Assert-Contains "script/installer-verification.ps1" 'privacy@kingkung\.men' "Verification helper publishes the deletion contact"
Assert-Contains "script/installer-verification.ps1" 'source code, prompts, project content' "Verification helper discloses excluded project data"
Assert-Contains "script/installer-verification.ps1" 'Display name \(required' "Verification helper requires the display name"
Assert-NotContains "script/installer-verification.ps1" 'if \(\$Yes\)' "Verification helper cannot be bypassed by -Yes"
Assert-Contains "script/install-codyx-global.ps1" 'call "\$repoLauncher" %\*' "CMD shim delegates to the repo launcher"
Assert-Contains "script/install-codyx-global.ps1" '\& "\$repoLauncher" @args' "PowerShell shim delegates to the repo launcher"
Assert-Contains "script/install-codyx-global.ps1" '\$launchShortcut\.Arguments = "/k' "Start Menu launcher keeps the console open"
Assert-Contains "script/install-codyx-global.ps1" 'adminUninstall[\s\S]*https://install\.kingkung\.men[\s\S]*receiptPath' "Global installer marker records admin uninstall metadata"
Assert-Contains "codyx.cmd" 'Press any key to close this window' "Menu launcher leaves errors visible before closing"
Assert-NotContains "script/install-codyx-global.ps1" '%~dp0\.\.\\\.\.\\codyx' "CMD shim has no guessed install path"
Assert-NotContains "script/install-codyx-global.ps1" '[^\x00-\x7F]' "Global installer is ASCII-safe for Windows PowerShell"
Assert-Contains "script/discover-local-models.ps1" '127\.0\.0\.1:11434/api/tags' "Model discovery uses the bounded Ollama API"
Assert-NotContains "script/discover-local-models.ps1" 'Ollama\.Ollama|winget install' "Model discovery does not install Ollama when missing"
Assert-Contains "script/install.ps1" 'Get-CodyxOllamaCommand[\s\S]*Ollama not found\. Local Ollama model discovery skipped\.' "Windows installer checks Ollama before asking to scan"
Assert-Contains "script/install.ps1" 'Scan local Ollama models now\? \[y/N\]' "Windows installer only asks for Ollama scan after detection"
Assert-Contains "script/discover-local-models.ps1" 'ArgumentList "serve"' "Model discovery starts the Ollama API when needed"
Assert-Contains "script/discover-local-models.ps1" 'ollamaStartedByCodyx' "Model discovery reports whether codyx started Ollama"
Assert-Contains "script/discover-local-models.ps1" 'ollamaCustomModelsPath' "Model discovery reports custom OLLAMA_MODELS paths"
Assert-NotContains "script/discover-local-models.ps1" 'ollama\.Source list|running: ollama list' "Model discovery does not invoke an unbounded Ollama process"
Assert-Contains "script/discover-local-models.ps1" 'CODY_GGUF_PATHS' "Model discovery supports explicit GGUF roots"
Assert-NotContains "script/discover-local-models.ps1" 'Get-PSDrive' "Model discovery does not crawl every fixed drive"
Assert-Contains "script/install.sh" 'GLOBAL_BIN_DIR="\$\{CODY_GLOBAL_BIN_DIR:-\$HOME/\.local/bin\}"' "Unix launcher uses the standard user bin"
Assert-Contains "script/install.sh" 'export CODY_INSTALL_ROOT=' "Unix launcher exports its install root"
Assert-Contains "script/install.sh" 'fish_add_path' "Unix installer writes valid Fish PATH syntax"
Assert-Contains "script/install.sh" 'Global command verified' "Unix installer verifies the global command"
Assert-Contains "script/install.sh" '\[ "\$YES" = "1" \] && \[ "\$REBOOT" = "1" \]' "Non-interactive server install does not reboot by default"
Assert-Contains "script/install.sh" 'bun_version_supported' "Unix installer enforces the supported Bun version"
Assert-Contains "script/install.sh" 'record_managed_tool "bun" "path"' "Unix installer records Bun only when it installs Bun"
Assert-Contains "script/install.sh" 'write_install_marker' "Unix installer writes the Codyx ownership marker"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'codyx-ai' "Uninstall uses the current package name"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" '\.local", "bin", "codyx"' "Uninstall removes the Unix global launcher"
Assert-NotContains "packages/codyx/src/cli/cmd/uninstall.ts" 'removeNpmPathEntry' "Uninstall preserves the shared npm PATH entry"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'managedTools' "Uninstall reads Codyx-owned tool markers"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'removeManagedTools' "Uninstall removes tools installed by Codyx"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'markedPaths[\s\S]*pathEntries[\s\S]*packageCommands' "Uninstall consumes live marker paths, PATH entries, and JS package commands"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'jsInstall[\s\S]*packageCommandForMethod' "Uninstall removes JS package installs recorded in the marker"
Assert-Contains "packages/codyx/src/cli/cmd/uninstall.ts" 'were not marked as installed by codyx, so they were left installed' "Uninstall preserves shared system tools"
Assert-Contains "packages/codyx/src/installation/command.ts" 'executeUninstall\("curl", targets\)' "Admin-triggered remote uninstall uses the full marker-based cleanup path"
Assert-Contains "packages/codyx/src/installation/index.ts" 'CODY_INSTALL_ROOT' "Installation method detection uses the install root"
Assert-Contains "packages/codyx/src/cli/upgrade.ts" 'CODY_INSTALL_ROOT' "Auto-update uses the install root"
Assert-NotContains "packages/codyx/src/cli/upgrade.ts" 'git rev-parse --git-dir' "Auto-update does not treat the user's current repo as the codyx install"
Assert-NotContains "packages/codyx/src/index.ts" 'git rev-parse --show-toplevel' "CLI entry point does not git-pull the user's current repo"
Assert-NotContains "packages/codyx/src/index.ts" 'system-state\.json' "CLI has no state-file deletion switch"
Assert-NotContains "packages/codyx/src/index.ts" 'rm -rf|rmdir /s /q' "CLI entry point cannot delete its checkout"
Assert-Contains ".gitignore" '\.codyx-install-marker' "Generated install marker is ignored"

if ($failures.Count -gt 0) {
  Write-Host "$($failures.Count) of $checks installer checks failed:" -ForegroundColor Red
  $failures | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
  exit 1
}

Write-Host "All $checks installer checks passed." -ForegroundColor Green
